### ISSUE TITLE
Possible to access web ui to manage database?

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb-mesos-framework#1]
I have just successfully launch ArangoDB on my test mesos cluster.

Previously I was using ArangoDB as a single database installed directly on Ubuntu. If I visit '/index.html`, I get a dashboard saying it's running a cluster.

Is there anyway to access the traditional ArangoDB web ui where I can see and add/delete collections and documents?

**Comment by mikestaub** [comment]
+1 this would be extremely useful

**Comment by mikestaub** [comment]
This can be closed as it is available in DC/OS 1.9, thanks!

**Comment by m0ppers** [comment]
good point
