### ISSUE TITLE
Unable to setup authentication for arangodb cluster on DC/OS

### ISSUE THREAD

**Issue by chanakyan-arivumani** [arangodb/arangodb-mesos-framework#18]
I'm facing the same issue that @nervetattoo reported in #10 
I tried the environment variables, but even after setting them and restarting my framework, the authentication flag remained false. 

> I tried manually getting the agency back by starting the docker containers again, but the framework had moved to a new node, so while the agency managed to work fine between itself, it was no longer part of the framework and nothing self-healed. I ended up wiping arangodb3 and restoring from backup because I realised this would cause downtime in some way. I theorised that a fresh deploy with the extra args for just the coordinator would work ...
Redeploying with the extra-args in an options.json worked the same way; It didnt. Framework started, but all tasks failed due to unknown args.

Same thing happened to me. If this issue is fixed, can someone please document the exact procedure to set those environment variables? Is there a better way to do this?

**Comment by dothebart** [comment]
ah, no thats been a misunderstanding. I was talking about upstream mesosphere / DC/OS.

**Comment by chanakyan-arivumani** [comment]
oops! my bad.
did you mean this one? [https://github.com/mesosphere/dcos-commons](url)

**Comment by dothebart** [comment]
The adminrouter is the component in charge of this: https://github.com/dcos/dcos/tree/master/packages/adminrouter/extra/src/

**Comment by chanakyan-arivumani** [comment]
Alright. Thanks!
