### ISSUE TITLE
Healthcheck fails (returns "null" string with 503 http response code)

### ISSUE THREAD

**Issue by soualid** [arangodb/arangodb-mesos-framework#19]
Hello,

We're trying to setup a arango-mesos-framework under DCOS 1.9.0 using the following configuration. Everything seems to start as expected, the web UI is even available and report that the 2 nodes are ok, but the framework healthcheck at `/service/arangodb/framework/v1/health.json` returns a `null` string and a 503 response code, which makes the framework being flagged as unhealthy by Marathon. Is this a known issue ?

```
{
  "id": "arangodb",
  "cpus": 0.25,
  "mem": 256.0,
  "ports": [0, 0, 0],
  "instances": 1,
  "args": [
    "framework",
    "--framework_name=arangodb",
    "--master=zk://172.16.0.5:2181/mesos",
    "--zk=zk://172.16.0.5:2181/arangodb",
    "--user=",
    "--principal=pri",
    "--role=arangodb",
    "--mode=cluster",
    "--async_replication=true",
    "--minimal_resources_agent=mem(*):512;cpus(*):0.25;disk(*):512",
    "--minimal_resources_dbserver=mem(*):512;cpus(*):0.25;disk(*):1024",
    "--minimal_resources_secondary=mem(*):512;cpus(*):0.25;disk(*):1024",
    "--minimal_resources_coordinator=mem(*):512;cpus(*):0.25;disk(*):1024",
    "--nr_agents=1",
    "--nr_dbservers=2",
    "--nr_coordinators=2",
    "--failover_timeout=86400",
    "--arangodb_image=arangodb/arangodb-mesos:3.2.8",
    "--secondaries_with_dbservers=false",
    "--coordinators_with_dbservers=false"
  ],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "arangodb/arangodb-mesos-framework:3.2-1.1.3",
      "network": "HOST"
    }
  },
  "healthChecks": [
    {
      "protocol": "HTTP",
      "path": "/framework/v1/health.json",
      "gracePeriodSeconds": 3,
      "intervalSeconds": 10,
      "portIndex": 0,
      "timeoutSeconds": 10,
      "maxConsecutiveFailures": 0
    }
  ]
}
```
Attached is the stderr and stdout logfiles. Please note the weird : 

```
E1121 22:08:56.680603    22 ArangoManager.cpp:339] numberOfDBServers in cluster target is not a number but null
```

in stderr.

[stderr.framework.log](https://github.com/arangodb/arangodb-mesos-framework/files/1493156/stderr.framework.log)
[stdout.framework.log](https://github.com/arangodb/arangodb-mesos-framework/files/1493159/stdout.framework.log)

**Comment by soualid** [comment]
Also, the following appears in `stderr` for the framework task : 

```E1121 21:11:10.513705    22 ArangoManager.cpp:339] numberOfDBServers in cluster target is not a number but null```

**Comment by soualid** [comment]
This issue is caused by the following part of the documentation, which states about `MESOS_ROLES` with the value `arangodb`, whereas the required value by the latest version of the framework is `arangodb3`.

> On mesosphere dcos edit /opt/mesosphere/etc/mesos-master and ensure the role is present:
> 
> MESOS_ROLES=slave_public,arangodb
> MESOS_WEIGHTS=slave_public=1,arangodb=1

**Comment by m0ppers** [comment]
Ooops...This section was referring how to install on a very old mesos version (0.26). Older versions needed to know roles beforehand. Sorry if that caused confusion. In versions later than 0.26 you don't have to specify roles beforehand so you should be able to simply undo that change.

Did everything work apart from that?

I will remove the README section. It is really not relevant anymore.

**Comment by soualid** [comment]
Yup, everything is ok since I set the proper roles on the master, many thanks !

Please note that if I remember rightly, the initial issue also appeared under DCOS 1.9 if the `MESOS_ROLES` and weights wasn't set before installing the universe package or the mesos framework directly, even if DCOS 1.9 use a recent version of Apache Mesos. 

I will be able to double check that since I have another cluster to setup, or close the ticket if it's not the case. Many thanks for your feedback.

**Comment by soualid** [comment]
I confirm that the `MESOS_ROLES` attributes are no longer required when running recent mesos version.
